import { API_ENDPOINTS } from '../config/apiConfig';
export const PROFORMA_INVOICE_GENERATE_URL = API_ENDPOINTS.PROFORMA_INVOICE_GENERATE;
export const INVOICE_GENERATE_URL = API_ENDPOINTS.INVOICE_GENERATE;

export const REQUEST_COMM_SET_URL =
  API_ENDPOINTS.REQUEST_COMM_SET;

export const COMM_EXPLOSION_URL =
  API_ENDPOINTS.COMM_EXPLOSION;

export const APPLICATION_REQUEST_PROFORMA_SET_URL =
  API_ENDPOINTS.APPLICATION_REQUEST_PROFORMA_INVOICE_SET;

export const PAYMENT_TRANS_DET_URL =
  API_ENDPOINTS.PAYMENT_TRANS_DET_GET;

export const PAYMENT_TRANS_SET_URL =
  API_ENDPOINTS.PAYMENT_TRANS_SET;

export const PAYMENT_SLIP_STATUS_SET_URL =
  API_ENDPOINTS.PAYMENT_SLIP_STATUS_SET;

export const INT_INVOICE_GET_URL =
  API_ENDPOINTS.INT_INVOICE_GET;

export const INT_INVOICE_DET_GET_URL =
  API_ENDPOINTS.INT_INVOICE_DET_GET;
